version: '3.4'

services:
  goyo_app_db:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${USER_DATABASE}
      MYSQL_USER: ${USER_USERNAME}
      MYSQL_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_USERNAME}
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    volumes:
      - data_volume:/var/lib/mysql
      - ${CONFIGURATION_PATH}:/docker-entrypoint-initdb.d:rw

volumes:
  data_volume:
    name: ${VOLUME_NAME}
